"""Gravity generated by a point mass in a local Cartesian frame.

Convention
----------
Coordinates are ``(x, y, z)`` in metres, with ``z`` positive upward. The returned
acceleration is the attraction at the observation point and therefore points from
the observation point toward a positive source mass. Negative mass anomalies are
allowed and reverse the direction. Outputs are in metres per second squared.
"""

from __future__ import annotations

import math
from collections.abc import Sequence

from oceangravity.constants import GRAVITATIONAL_CONSTANT

Vector3 = tuple[float, float, float]


def _as_finite_vector3(name: str, value: Sequence[float]) -> Vector3:
    """Validate and convert a coordinate-like sequence to a finite 3-vector."""

    if len(value) != 3:
        raise ValueError(f"{name} must contain exactly three coordinates")
    vector = (float(value[0]), float(value[1]), float(value[2]))
    if not all(math.isfinite(component) for component in vector):
        raise ValueError(f"{name} must contain only finite coordinates")
    return vector


def gravity_vector(
    mass_kg: float,
    source_xyz_m: Sequence[float],
    observation_xyz_m: Sequence[float],
) -> Vector3:
    """Return point-mass gravitational acceleration at an observation point.

    Parameters
    ----------
    mass_kg:
        Signed source mass or mass anomaly in kilograms.
    source_xyz_m:
        Source coordinates ``(x, y, z)`` in metres.
    observation_xyz_m:
        Observation coordinates ``(x, y, z)`` in metres in the same frame.

    Raises
    ------
    ValueError
        If the mass/coordinates are non-finite, a coordinate does not have three
        components, or source and observation are coincident.
    """

    mass = float(mass_kg)
    if not math.isfinite(mass):
        raise ValueError("mass_kg must be finite")

    source = _as_finite_vector3("source_xyz_m", source_xyz_m)
    observation = _as_finite_vector3("observation_xyz_m", observation_xyz_m)
    displacement = tuple(source[i] - observation[i] for i in range(3))
    distance_squared = sum(component * component for component in displacement)
    if distance_squared == 0.0:
        raise ValueError("point-mass gravity is singular at the source location")

    inverse_distance_cubed = 1.0 / (distance_squared * math.sqrt(distance_squared))
    scale = GRAVITATIONAL_CONSTANT.value * mass * inverse_distance_cubed
    return (
        scale * displacement[0],
        scale * displacement[1],
        scale * displacement[2],
    )


def vertical_gravity(
    mass_kg: float,
    source_xyz_m: Sequence[float],
    observation_xyz_m: Sequence[float],
) -> float:
    """Return the upward-positive vertical component in metres per second squared."""

    return gravity_vector(mass_kg, source_xyz_m, observation_xyz_m)[2]
